Encryption
ECS153/final-project-the-tigers pull request #6
Opened 2020-05-27 06:16 UTC by rmsepic

The file Crypto is a set of functions that I made so that we can encrypt any information that we need to send. My tests are currently with the chat functionality, however, they shouldn't be written that way, I was just trying to send the public key in whatever way I could to test it. 

There will be a design doc along with this PR, and I am putting this up more to receive feedback then to actually get this merged to master. It still needs a bit more work.

2020-05-28 03:48 UTC, steubs requested changes

2020-05-28 03:48 UTC, steubs commented on Seda/Seda/Crypto.swift
> +        guard let privateKey = SecKeyCreateRandomKey(attributes as CFDictionary, &err) else {
I'm getting "Thread 1: EXC_BAD_ACCESS (code=1, address=0x18)" at this line.

Might be related to this: https://stackoverflow.com/questions/12437605/thread-1-exc-bad-access-code-1-address-0x30000008-issue-generated

2020-05-28 03:48 UTC, steubs commented on Seda/Seda/Crypto.swift
> +            print("Crypto.loadPrivKey(): Error in retrieving the private key")
While I get the above error (EXC_BAD_ACCESS), this line is printed to the console.

2020-06-01 04:41 UTC, rmsepic commented
UPDATE 31st May

I have added friending and end-to-end encryption with the chat app. There was a good bit added to the chat app, so DJ if you want I can move it somewhere else. 

Also, the private key is no longer being stored within the enclave of the phone but within the keychain. It works now in the simulator, but there may be issues when trying to switch devices. 

For testing, I used my phone and a computer, and was able to send and recieve a friend request and message myself.

2020-06-02 05:25 UTC, rmsepic commented
Another update on the PR, turns out the issue DJ spotted was not with storage but having to do with friending. Currently storing it on the keychain associated with the **device**, so it can be run in the simulator and will work, however, it will store unique private keys on each simulator device. So I would suggest trying to keep different accounts for each device in the simulator and device as to not mix up the keys.

2020-06-03 03:07 UTC, Dong-Jie-Chen approved these changes

2020-06-03 16:34 UTC, merged